### ISSUE TITLE
'IOError: [Errno 2] No such file or directory' when starting a thread

### ISSUE THREAD

**Issue by kasimirmoi** [blobmon/simplechan#1]
Currently testing simplechan on a virtual machine. I am not very familiar with python and databases, so I'm not able to solve this by myself. When I try to start a thread, it seems like the server doesn't store the file on the server:
> Traceback (most recent call last):
  File "/home/user/simplechan/simplechan/venv/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/user/simplechan/simplechan/venv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/user/simplechan/simplechan/venv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/simplechan/simplechan/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/simplechan/simplechan/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/simplechan/simplechan/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/simplechan/simplechan/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/simplechan/simplechan/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/simplechan/simplechan/app/app/__init__.py", line 70, in start_thread
    return handler.handle_start_thread()
  File "/home/user/simplechan/simplechan/app/app/handler.py", line 252, in handle_start_thread
    img_verify_result = blob_handler.verify(app.config['UPLOAD_FOLDER'])
  File "/home/user/simplechan/simplechan/app/app/blobHandler.py", line 35, in verify
    verify_image_res = self.verify_image()
  File "/home/user/simplechan/simplechan/app/app/blobHandler.py", line 193, in verify_image
    self.filesize = BlobHandler.bytes_2_human_readable( self.save_tmp_image_and_return_img_size() )
  File "/home/user/simplechan/simplechan/app/app/blobHandler.py", line 202, in save_tmp_image_and_return_img_size
    self.blob_file.save( savepath_tmp )
  File "/home/user/simplechan/simplechan/venv/lib/python2.7/site-packages/werkzeug/datastructures.py", line 2725, in save
    dst = open(dst, 'wb')
IOError: [Errno 2] No such file or directory: '/user/home/simplechan/simplechan/app/app/images/tmp_1518974296579073.gif'

What could be causing this and how to solve it? Thank you.

**Comment by kasimirmoi** [comment]
Well, the problem was a typo in the appconfig.cfg file in the upload path... The files are now uploaded to the server without problems. My new problem is that the files are not displaying in the web-page, I'll look into it.

**Comment by 000azax** [comment]
I am having the same problem. Did you solve? Please let me know if you solve it

**Comment by kasimirmoi** [comment]
It's been a while but the problem was in the config files having conflicting settings. The files would upload to the server but they went to a folder that was different from the folder specified in one of the config files (can't remember which one). I suggest you go through the folders and find where the uploaded images/other files go and make sure the config files match that.

**Comment by 000azax** [comment]
Excuse me. It was difficult and I could not understand it. Specifically, please tell me how you edited the file so you can do it! ! By the way, I got an error when editing UPLOAD_PATH of appconfig. I made issume on that, so I would like you to reply there if possible! !
